# Generated by Django 3.0.4 on 2021-01-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cafe/')),
            ],
            options={
                'verbose_name': 'Kafe',
                'verbose_name_plural': 'Kafe',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=31)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Mektub',
                'verbose_name_plural': 'Mektub',
            },
        ),
        migrations.CreateModel(
            name='FlowerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitrin', models.IntegerField(default=2)),
                ('marsipan', models.IntegerField(default=2)),
                ('flower', models.IntegerField(default=2)),
                ('xonca', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='MarsipanCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('surname', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=63)),
                ('city', models.CharField(default='Baki', max_length=63)),
                ('address', models.CharField(max_length=63)),
                ('address2', models.CharField(blank=True, max_length=63, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('orderid', models.IntegerField(unique=True)),
                ('sessionid', models.CharField(max_length=127, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('pan', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=15)),
            ],
            options={
                'verbose_name': 'Sifaris',
                'verbose_name_plural': 'Sifaris',
            },
        ),
        migrations.CreateModel(
            name='VitrinCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='XoncaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Xonca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=511, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='xonca/')),
                ('publish', models.BooleanField(default=True)),
                ('homepage', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.XoncaCategory')),
                ('similar1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar1_of', to='api.Xonca')),
                ('similar2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar2_of', to='api.Xonca')),
                ('similar3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar3_of', to='api.Xonca')),
                ('similar4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar4_of', to='api.Xonca')),
            ],
            options={
                'verbose_name': 'Xonca',
                'verbose_name_plural': 'Xonca',
            },
        ),
        migrations.CreateModel(
            name='Vitrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=5.9, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=511, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vitrin/')),
                ('publish', models.BooleanField(default=True)),
                ('homepage', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.VitrinCategory')),
                ('similar1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar1_of', to='api.Vitrin')),
                ('similar2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar2_of', to='api.Vitrin')),
                ('similar3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar3_of', to='api.Vitrin')),
                ('similar4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar4_of', to='api.Vitrin')),
            ],
            options={
                'verbose_name': 'Vitrin',
                'verbose_name_plural': 'Vitrin',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=31, null=True)),
                ('quantity', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Marsipan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=511, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marsipan/')),
                ('publish', models.BooleanField(default=True)),
                ('homepage', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MarsipanCategory')),
                ('similar1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar1_of', to='api.Marsipan')),
                ('similar2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar2_of', to='api.Marsipan')),
                ('similar3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar3_of', to='api.Marsipan')),
                ('similar4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar4_of', to='api.Marsipan')),
            ],
            options={
                'verbose_name': 'Marsipan',
                'verbose_name_plural': 'Marsipan',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=511, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower/')),
                ('publish', models.BooleanField(default=True)),
                ('homepage', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FlowerCategory')),
                ('similar1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar1_of', to='api.Flower')),
                ('similar2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar2_of', to='api.Flower')),
                ('similar3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar3_of', to='api.Flower')),
                ('similar4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar4_of', to='api.Flower')),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flower',
            },
        ),
    ]
