# Generated by Django 3.0.4 on 2020-12-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderproduct_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
