# Generated by Django 3.0.4 on 2021-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210211_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_facebook', models.IntegerField(blank=True, null=True)),
                ('to_instagram', models.IntegerField(blank=True, null=True)),
                ('from_facebook', models.IntegerField(blank=True, null=True)),
                ('from_instagram', models.IntegerField(blank=True, null=True)),
                ('from_oxu_az', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': "Sosial medya backlink'ləri",
            },
        ),
        migrations.AlterModelOptions(
            name='flowercategory',
            options={'verbose_name_plural': 'Gül kateqoriyaları'},
        ),
    ]
