# Generated by Django 3.0.4 on 2021-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210213_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialMedia',
        ),
    ]
