# Generated by Django 3.0.4 on 2020-12-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201222_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
