# Generated by Django 3.0.4 on 2021-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210213_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name_plural': 'Gül'},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='from_facebook',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='from_instagram',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='from_oxu_az',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='to_facebook',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='to_instagram',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
