# Generated by Django 3.1.2 on 2020-10-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201031_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='marsipan',
            name='category',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.marsipancategory', verbose_name='category'),
        ),
    ]
