# Generated by Django 3.0.4 on 2021-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210213_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=31)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Backlink IP'ləri",
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Mektublar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Sifarislər'},
        ),
    ]
