# Generated by Django 3.1.2 on 2020-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201031_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.9, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='marsipan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=6, null=True),
        ),
    ]
