# Generated by Django 3.0.4 on 2021-02-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210213_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marsipancategory',
            options={'verbose_name_plural': 'Marsipan kateqoriyaları'},
        ),
    ]
