# Generated by Django 3.1.2 on 2020-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_flower_flowercategory_xonca_xoncacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, default='arivals-2.jpg', null=True, upload_to='img/vitrin'),
        ),
    ]
