# Generated by Django 3.0.4 on 2020-11-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201113_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='similar1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake1', to='api.Cake'),
        ),
        migrations.AddField(
            model_name='cake',
            name='similar2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake2', to='api.Cake'),
        ),
        migrations.AddField(
            model_name='cake',
            name='similar3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake3', to='api.Cake'),
        ),
        migrations.AddField(
            model_name='cake',
            name='similar4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake4', to='api.Cake'),
        ),
    ]
