"""
Django settings for purple project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUD", os.path.join(BASE_DIR, ".env"))

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", os.path.join(BASE_DIR, ".env"))

CORS_ORIGIN_ALLOW_ALL = os.environ.get("CORS_ORIGIN_ALLOW_ALL", os.path.join(BASE_DIR, ".env"))

# Application definition

INSTALLED_APPS = os.environ.get("INSTALLED_APPS", os.path.join(BASE_DIR, ".env"))

MIDDLEWARE = os.environ.get("MIDDLEWARE", os.path.join(BASE_DIR, ".env"))

ROOT_URLCONF = os.environ.get("ROOT_URLCONF", os.path.join(BASE_DIR, ".env"))

TEMPLATES = os.environ.get("TEMPLATES", os.path.join(BASE_DIR, ".env"))

WSGI_APPLICATION = os.environ.get("WSGI_APPLICATION", os.path.join(BASE_DIR, ".env"))


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = os.environ.get("DATABASES", os.path.join(BASE_DIR, ".env"))

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = os.environ.get("AUTH_PASSWORD_VALIDATORS", os.path.join(BASE_DIR, ".env"))


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", os.path.join(BASE_DIR, ".env"))

TIME_ZONE = os.environ.get("TIME_ZONE", os.path.join(BASE_DIR, ".env"))

USE_I18N = os.environ.get("USE_I18N", os.path.join(BASE_DIR, ".env"))

USE_L10N = os.environ.get("USE_L10N", os.path.join(BASE_DIR, ".env"))

USE_TZ = os.environ.get("USE_TZ", os.path.join(BASE_DIR, ".env"))


STATIC_URL = os.environ.get("STATIC_URL", os.path.join(BASE_DIR, ".env"))
STATIC_ROOT = os.environ.get("STATIC_ROOT", os.path.join(BASE_DIR, ".env"))
MEDIA_URL = os.environ.get("MEDIA_URL", os.path.join(BASE_DIR, ".env"))
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", os.path.join(BASE_DIR, ".env"))
NEXT_APP = '/../frontend/'
